export const GET_ERRORS = "GET_ERRORS";
export const GET_COMPTE = "GET_COMPTE";
export const GET_DEMANDE = "GET_DEMANDE";
export const GET_DEMANDEBYID = "GET_DEMANDEBYID";
export const GET_DEMANDEBYCOMPTE = "GET_DEMANDEBYCOMPTE";
export const GET_DEMANDEBYCOMPTEandSTATUT = "GET_DEMANDEBYCOMPTEandSTATUT";
export const GET_DEMANDEBYSTATUT = "GET_DEMANDEBYSTATUT";
export const GET_DEMANDEBYDATE = "GET_DEMANDEBYDATE";
export const GET_DEMANDEBYDATEETSTATUT = "GET_DEMANDEBYDATEETSTATUT";
export const GET_DEMANDEBYDATEETCOMPTE = "GET_DEMANDEBYDATEETCOMPTE";
export const GET_DEMANDEBYDATEETCOMPTEETSTATUT =
  "GET_DEMANDEBYDATEETCOMPTEETSTATUT";
export const GET_ABONNEE = "GET_ABONNEE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
